# Generated by Django 3.2 on 2021-04-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('street_name', models.CharField(blank=True, max_length=20)),
                ('house_no', models.IntegerField(blank=True)),
                ('flat_no', models.IntegerField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('dicom_location', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('study_date', models.DateField()),
                ('age', models.IntegerField(blank=True)),
                ('modalities', models.CharField(blank=True, max_length=30)),
                ('body_parts', models.CharField(blank=True, max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjenci.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_num', models.IntegerField()),
                ('date', models.DateField()),
                ('body_part', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjenci.studies')),
            ],
        ),
        migrations.CreateModel(
            name='DICOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacjenci.series')),
            ],
        ),
    ]
