# Generated by Django 3.2 on 2021-04-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dicom_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
