# Generated by Django 3.2 on 2021-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0002_auto_20210427_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='dicom_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
