# Generated by Django 3.2 on 2021-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0002_auto_20210427_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='xray_type',
            field=models.CharField(blank=True, choices=[('RTG', 'Rentgen'), ('MRI', 'Magnetic resonance'), ('Other', 'Other x-ray type')], max_length=5),
        ),
    ]
