# Generated by Django 3.2 on 2021-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0003_studies_xray_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studies',
            name='xray_type',
        ),
        migrations.AddField(
            model_name='dicom',
            name='dicom_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
