# Generated by Django 3.2 on 2021-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0004_auto_20210527_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='instance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
