# Generated by Django 3.2 on 2021-05-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0005_auto_20210527_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='instance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
