# Generated by Django 3.2 on 2021-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0006_auto_20210527_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
