# Generated by Django 3.2 on 2021-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacjenci', '0007_alter_dicom_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicom',
            name='location',
        ),
        migrations.AddField(
            model_name='dicom',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
